/*
 * This file is part of KFParticle package
 * Copyright (C) 2007-2026
 *
 * KFParticle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#ifndef KFPARTICLEGPUCPUCHANNELCATALOGUE_H
#define KFPARTICLEGPUCPUCHANNELCATALOGUE_H

#include "KFParticleGpuDecayGraph.h"

#include <array>
#include <vector>

class KFParticleGpuDecayPlan;
struct KFParticleGpuEventDesc;

enum KFParticleGpuCpuChannelActivation : unsigned int
{
  KFGpuCpuChannelActive = 0u,
  KFGpuCpuChannelConditionalInput = 1u,
  KFGpuCpuChannelConfigurationDisabled = 2u,
  KFGpuCpuChannelActivationCount = 3u
};

enum KFParticleGpuCpuChannelInput : unsigned int
{
  KFGpuCpuInputTracks = 1u << 0u,
  KFGpuCpuInputPrimaryVertices = 1u << 1u,
  KFGpuCpuInputChiToPrimaryVertex = 1u << 2u,
  KFGpuCpuInputNeutralCandidates = 1u << 3u
};

/** One stable, host-side contract for an active or explicitly disabled CPU channel. */
struct KFParticleGpuCpuChannelContract
{
  unsigned int channelId = 0u;
  unsigned int conjugateChannelId = 0u;
  unsigned int family = KFGpuCpuFamilyCount;
  int motherPdg = 0;
  int firstDaughterPdg = 0;
  int secondDaughterPdg = 0;
  unsigned int topology = KFGpuGraphTopologyInvalid;
  unsigned int generation = 0u;
  unsigned int firstSourceKind = KFGpuGraphSourceNone;
  unsigned int secondSourceKind = KFGpuGraphSourceNone;
  unsigned int parentChannelId = 0u;
  unsigned int secondParentChannelId = 0u;
  unsigned int operationMask = 0u;
  unsigned int daughterHypothesisProfile = 0u;
  unsigned int selectionProfile = 0u;
  unsigned int outputClass = KFGpuGraphOutputInvalid;
  unsigned int requiredInputs = 0u;
  unsigned int activation = KFGpuCpuChannelActive;
  unsigned int supportStatus = KFGpuGraphUnsupported;
  unsigned int unsupportedReason = KFGpuGraphUnsupportedNotImplemented;
};

struct KFParticleGpuCpuChannelCoverage
{
  unsigned int channelId = 0u;
  unsigned int family = KFGpuCpuFamilyCount;
  unsigned int activation = KFGpuCpuChannelActive;
  unsigned int supportStatus = KFGpuGraphUnsupported;
  unsigned int unsupportedReason = KFGpuGraphUnsupportedNotImplemented;
};

/** Machine-checkable accounting for one complete-input CPU finder plan. */
struct KFParticleGpuCpuFinderCoverageSummary
{
  std::array<unsigned int, KFGpuCpuFamilyCount> requiredByFamily = {};
  std::array<unsigned int, KFGpuCpuFamilyCount> implementedByFamily = {};
  std::array<unsigned int, KFGpuCpuFamilyCount> disabledByFamily = {};
  unsigned int catalogueChannels = 0u;
  unsigned int requiredChannels = 0u;
  unsigned int implementedChannels = 0u;
  unsigned int disabledChannels = 0u;
  unsigned int unsupportedChannels = 0u;

  bool Complete() const
  {
    return requiredChannels == implementedChannels
      && unsupportedChannels == 0u
      && catalogueChannels == requiredChannels + disabledChannels;
  }
};

const std::vector<KFParticleGpuCpuChannelContract>&
KFParticleGpuCpuChannelCatalogue();

void ValidateKFParticleGpuCpuChannelCatalogue(
  const std::vector<KFParticleGpuCpuChannelContract>& catalogue);

std::vector<KFParticleGpuCpuChannelCoverage>
MakeCpuFinderChannelCoverage(const KFParticleGpuDecayPlan& plan);

std::vector<KFParticleGpuGraphFamilyCoverage>
MakeCpuFinderFamilyCoverage(
  const std::array<unsigned int, KFGpuCpuFamilyCount>& implementedCounts);

void AddCpuFinderTwoDaughterChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderCompositeTrackChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderCompositeCompositeChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderPrimaryProjectionChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderNeutralMissingMassChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderKaonMatchingChannels(KFParticleGpuDecayPlan& plan);
void AddCpuFinderFinalSelectionChannels(KFParticleGpuDecayPlan& plan);

/** Build the dependency-complete plan containing every declared active channel. */
void AddCompleteCpuFinderChannels(KFParticleGpuDecayPlan& plan);

/** Build only requested CPU outputs and the intermediate channels they depend on. */
void AddRequestedCpuFinderChannels(KFParticleGpuDecayPlan& plan,
                                   const std::vector<int>& requestedMotherPdgs);

KFParticleGpuCpuFinderCoverageSummary
MakeCompleteCpuFinderCoverageSummary(const KFParticleGpuDecayPlan& plan);

void ValidateCompleteCpuFinderPlan(const KFParticleGpuDecayPlan& plan);

/** Upper bound for raw-track pair tasks generated by a declared CPU plan. */
unsigned int KFParticleGpuCpuFinderRawTaskCapacity(
  const KFParticleGpuEventDesc& event,
  const KFParticleGpuDecayPlan& plan);

unsigned long long KFParticleGpuCpuChannelCatalogueRevision();

static_assert(KFGpuCpuFamilyCount == 9u,
              "the frozen CPU catalogue must be updated when a finder family is added");

#endif
